name: Qdrant Edge Tests

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ '**' ]

jobs:
  edge-py-test:
    name: Test Python bindings

    runs-on: ubuntu-latest

    services:
      # Required by lib/edge/python/examples/optimize.py
      qdrant:
        image: qdrant/qdrant:v1.17.0
        ports:
          - 6333:6333
          - 6334:6334

    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install mold
        uses: rui314/setup-mold@v1

      - name: Enable mold
        run: |
          mkdir .cargo

          cat >.cargo/config.toml <<-EOF
          [target.x86_64-unknown-linux-gnu]
          linker = "clang"
          rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/mold"]
          EOF

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install maturin
        run: pip install maturin

      - name: Checkout Qdrant
        uses: actions/checkout@v6

      - name: Restore Rust build cache
        uses: Swatinem/rust-cache@v2

      - name: Build Qdrant Edge
        run: |
          cd lib/edge/python

          python -m venv .venv
          source .venv/bin/activate

          pip install requests
          maturin develop --no-default-features --features abi3

      - name: Wait for Qdrant
        run: curl -sf --retry 30 --retry-delay 1 --retry-all-errors http://localhost:6333 >/dev/null

      - name: Run all Python example scripts
        run: |
          cd lib/edge/python
          source .venv/bin/activate

          for fname in examples/*.py; do
            case "$(basename "$fname")" in
              __init__.py) continue ;;
              download_partial.py) continue ;; # Not edge test
              # optimize.py) continue ;; # FIXME
            esac
            echo "::group::Running example: $fname"
            python "$fname"
            echo "::endgroup::"
          done
